// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoU9zwrRDGZeAdp4a9KiN_HKXU-RpkcKw',
    appId: '1:627039625663:android:3366456b66317fcbd8410a',
    messagingSenderId: '627039625663',
    projectId: 'my-ecommerce-app-123-80779',
    storageBucket: 'my-ecommerce-app-123-80779.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdpqg1DfNQoAYPKzvohHbO23C-uAmDzq4',
    appId: '1:627039625663:web:4db59f59e95d486ed8410a',
    messagingSenderId: '627039625663',
    projectId: 'my-ecommerce-app-123-80779',
    authDomain: 'my-ecommerce-app-123-80779.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-80779.firebasestorage.app',
    measurementId: 'G-YZZCG2HFFL',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdpqg1DfNQoAYPKzvohHbO23C-uAmDzq4',
    appId: '1:627039625663:web:d7197d0966e66816d8410a',
    messagingSenderId: '627039625663',
    projectId: 'my-ecommerce-app-123-80779',
    authDomain: 'my-ecommerce-app-123-80779.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-80779.firebasestorage.app',
    measurementId: 'G-YZNM0D2BVB',
  );

}